### ISSUE TITLE
Run tests error on setupAll

### ISSUE THREAD

**Issue by lucasdidur** [adryanev/flutter-mobile-clean-architecture-template#9]
```
MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
dart:async                                                _Completer.completeError
SharedPreferences.getInstance
shared_preferences.dart:38
===== asynchronous gap ===========================
dart:async                                                _CustomZone.registerBinaryCallback
SharedPreferences.getInstance
shared_preferences.dart:33
StorageModule.sharedPreference
storage_module.dart:8
GetItInjectableX.init.<fn>
injector.config.dart:33
GetItHelper.lazySingletonAsync
get_it_helper.dart:165
GetItInjectableX.init
injector.config.dart:32
configureDependencies
injector.dart:8
configureInjector
configure_injector.dart:5
```

**Comment by adryanev** [comment]
Hi, thank you for opening an issue.
could you possible send a snippet of the code that trigger the error above?

Thank you

**Comment by adryanev** [comment]
> MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
> dart:async                                                _Completer.completeError
> SharedPreferences.getInstance
> shared_preferences.dart:38
> ===== asynchronous gap ===========================
> dart:async                                                _CustomZone.registerBinaryCallback
> SharedPreferences.getInstance
> shared_preferences.dart:33
> StorageModule.sharedPreference
> storage_module.dart:8
> GetItInjectableX.init.<fn>
> injector.config.dart:33
> GetItHelper.lazySingletonAsync
> get_it_helper.dart:165
> GetItInjectableX.init
> injector.config.dart:32
> configureDependencies
> injector.dart:8
> configureInjector
> configure_injector.dart:5

Hi, thank you for opening an issue.
could you possible send a snippet of the code that trigger the error above?

Thank you

**Comment by lucasdidur** [comment]
@adryanev Its the project itself using the last flutter version
